services:
  django:
    image: ghcr.io/delanoche92/projet_cms:latest
    container_name: monprojet_prod_django
    restart: always
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/monprojet/media
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: monprojet_prod_postgres
    restart: always
    volumes:
      - monprojet_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:7
    container_name: monprojet_prod_redis
    restart: always

  nginx:
    image: nginx:1.25
    container_name: monprojet_prod_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/monprojet/media
    depends_on:
      - django
    # --- AJOUT FINAL ---
    # On force Nginx à attendre 5 secondes que Django soit prêt
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"

volumes:
  monprojet_prod_postgres_data:
  staticfiles_volume:
  media_volume:
