---
prometheus_version: "latest"
prometheus_dir: "/opt/prometheus"
prometheus_port: 9090
prometheus_retention: "15d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

prometheus_targets:
  - name: "vm-support"
    endpoint: "10.20.1.10:9100"
  - name: "vm-elk"
    endpoint: "10.20.1.11:9100"
  - name: "vm-rh"
    endpoint: "10.30.1.11:9100"

